sudo: required
dist: trusty
language: python
python:
  - '3.6'
install:
  - pip install --quiet -r ci/requirements.txt && pip install coveralls pylint
  - git clone https://github.com/"${TRAVIS_REPO_SLUG%%/*}"/vanir-builder ~/vanir-builder
script:
  - PYTHONPATH=test-packages pylint --rcfile=ci/pylintrc vanir vanirpolicy
  - ./run-tests --no-syslog
  - ~/vanir-builder/scripts/travis-
  - python manage.py collectstatic --noinput
  - coverage run --rcfile .coveragerc manage.py test
  - pylint devel main mirrors news packages releng templates todolists visualize *.py
  
env:
 - DIST_DOM0=fc25 USE_VANIR_REPO_VERSION=4.0 USE_VANIR_REPO_TESTING=1
 - DIST_DOM0=fc29 USE_VANIR_REPO_VERSION=4.0 USE_VANIR_REPO_TESTING=1

after_success:
  - codecov -F unittests
  - ~/vanir-builder/scripts/travis-deploy
  - coveralls

# don't build tags which are meant for code signing only
branches:
  except:
    - /.*_.*/

addons:
  apt:
    packages:
      - debootstrap

# vim: ts=2 sts=2 sw=2 et
