#!/usr/bin/python3

from vaniradmin import Vanir

def main():
    app = Vanir()
    for vm in app.domains:
        if vm.klass == 'DispVM' and not vm.is_running():
            if vm.auto_cleanup:
                del app.domains[vm.name]

main()
