all:
	true

install:
	mkdir -p $(DESTDIR)/usr/lib/vanir
	cp cleanup-dispvms $(DESTDIR)/usr/lib/vanir
	cp startup-misc.sh $(DESTDIR)/usr/lib/vanir
	cp fix-dir-perms.sh $(DESTDIR)/usr/lib/vanir/
