import datetime
import vanir.ext
import vanir.firewall
import vanir.vm.vanirvm
import vanir.vm.appvm
import vanir.vm.templatevm
import vanir.utils

yum_proxy_ip = '10.137.255.254'
yum_proxy_port = '8082'


class R3Compatibility(vanir.ext.Extension):
    '''Maintain VM interface compatibility with R3.0 and R3.1.
    At least where possible.
    '''

    features_to_services = {
        'service.ntpd': 'ntpd',
        'check-updates': 'vanir-update-check',
        'dvm': 'vanir-dvm',

    }

    # noinspection PyUnusedLocal
    @vanir.ext.handler('domain-qdb-create')
    def on_domain_qdb_create(self, vm, event):
        '''
        :param vanir.vm.vanirvm.VanirVM vm: \
            VM on which VanirDB entries were just created
        ''' # pylint: disable=unused-argument
        # /vanir-vm-type: AppVM, NetVM, ProxyVM, TemplateVM
        if isinstance(vm, vanir.vm.templatevm.TemplateVM):
            vmtype = 'TemplateVM'
        elif vm.netvm is not None and vm.provides_network:
            vmtype = 'ProxyVM'
        elif vm.netvm is None and vm.provides_network:
            vmtype = 'NetVM'
        else:
            vmtype = 'AppVM'
        vm.untrusted_qdb.write('/vanir-vm-type', vmtype)

        vm.untrusted_qdb.write("/vanir-iptables-error", '')
        self.write_iptables_vanirdb_entry(vm)

        self.write_services(vm)

    @vanir.ext.handler('domain-spawn')
    def on_domain_started(self, vm, event, **kwargs):
        # pylint: disable=unused-argument
        if vm.netvm:
            self.write_iptables_vanirdb_entry(vm.netvm)

    @vanir.ext.handler('firewall-changed')
    def on_firewall_changed(self, vm, event):
        # pylint: disable=unused-argument
        if vm.is_running() and vm.netvm:
            self.write_iptables_vanirdb_entry(vm.netvm)

    def write_iptables_vanirdb_entry(self, firewallvm):
        # pylint: disable=no-self-use
        # skip compatibility rules if new format support is advertised
        if firewallvm.features.check_with_template('vanir-firewall', False):
            return
        firewallvm.untrusted_qdb.rm("/vanir-iptables-domainrules/")
        iptables = "# Generated by Vanir Core on {0}\n".format(
            datetime.datetime.now().ctime())
        iptables += "*filter\n"
        iptables += ":INPUT DROP [0:0]\n"
        iptables += ":FORWARD DROP [0:0]\n"
        iptables += ":OUTPUT ACCEPT [0:0]\n"

        # Strict INPUT rules
        iptables += "-A INPUT -i vif+ -p udp -m udp --dport 68 -j DROP\n"
        iptables += "-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED " \
                    "-j ACCEPT\n"
        iptables += "-A INPUT -p icmp -j ACCEPT\n"
        iptables += "-A INPUT -i lo -j ACCEPT\n"
        iptables += "-A INPUT -j REJECT --reject-with icmp-host-prohibited\n"

        iptables += "-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED " \
                    "-j ACCEPT\n"
        # Deny inter-VMs networking
        iptables += "-A FORWARD -i vif+ -o vif+ -j DROP\n"
        iptables += "COMMIT\n"
        firewallvm.untrusted_qdb.write("/vanir-iptables-header", iptables)

        for vm in firewallvm.connected_vms:
            iptables = "*filter\n"
            conf = vm.firewall

            xid = vm.xid
            if xid < 0:  # VM not active ATM
                continue

            ip = vm.ip
            if ip is None:
                continue

            # Anti-spoof rules are added by vif-script (vif-route-vanir),
            # here we trust IP address

            for rule in conf.rules:
                if rule.specialtarget == 'dns':
                    if rule.dstports not in ('53', None):
                        continue
                    if rule.proto:
                        protos = {'tcp', 'udp'}.intersection(str(rule.proto))
                    else:
                        protos = {'tcp', 'udp'}
                    for proto in protos:
                        if rule.dsthost:
                            dsthosts = set(vm.dns).intersection(
                                [str(rule.dsthost).replace('/24', '')])
                        else:
                            dsthosts = vm.dns
                        for dsthost in dsthosts:
                            iptables += '-A FORWARD -s {}'.format(ip)
                            iptables += ' -d {!s}'.format(dsthost)
                            iptables += ' -p {!s}'.format(proto)
                            iptables += ' --dport 53'
                            iptables += ' -j {}\n'.format(
                                str(rule.action).upper())
                else:
                    iptables += '-A FORWARD -s {}'.format(ip)
                    if rule.dsthost:
                        iptables += ' -d {!s}'.format(rule.dsthost)
                    if rule.proto:
                        iptables += ' -p {!s}'.format(rule.proto)
                    if rule.dstports:
                        iptables += ' --dport {}'.format(
                            str(rule.dstports).replace('-', ':'))
                    iptables += ' -j {0}\n'.format(str(rule.action).upper())

            iptables += '-A FORWARD -s {0} -j {1}\n'.format(ip,
                str(conf.policy).upper())
            iptables += 'COMMIT\n'
            firewallvm.untrusted_qdb.write(
                '/vanir-iptables-domainrules/' + str(xid),
                iptables)
        # no need for ending -A FORWARD -j DROP, cause default action is DROP

        firewallvm.untrusted_qdb.write('/vanir-iptables', 'reload')

    def write_services(self, vm):
        for feature, value in vm.features.items():
            service = self.features_to_services.get(feature, None)
            if service is None:
                continue
            # forcefully convert to '0' or '1'
            vm.untrusted_qdb.write('/vanir-service/{}'.format(service),
                str(int(bool(value))))
        if 'updates-proxy-setup' in vm.features.keys():
            vm.untrusted_qdb.write(
                '/vanir-service/{}'.format('yum-proxy-setup'),
                str(int(bool(vm.features['updates-proxy-setup']))))